### ISSUE TITLE
ошибка выполнения скрипта no attribute 'MorphAnalyzer'

### ISSUE THREAD

**Issue by tomatolog** [kmike/pymorphy2#139]
при выполнении скрипта с именем `tokenize.py` и содержанием
```
import pymorphy2

print (dir(pymorphy2))

morph = pymorphy2.MorphAnalyzer()

word = 'test'
res = morph.parse(word)
print(res[0].normal_form)
```

python выдает ошибку `AttributeError: 'module' object has no attribute 'MorphAnalyzer'` так же `dir(pymorphy2)` показывает отсутвие метода MorphAnalyzer у модуля - `print (dir(pymorphy2))`
```
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'dawg', 'opencorpora_dict', 'tagset', 'utils', 'version']
```

traceback:
```
C:\dev\>python tokenize.py
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'dawg', 'opencorpora_dict', 'tagset', 'utils', 'version']
Traceback (most recent call last):
  File "tokenize.py", line 1, in <module>
    import pymorphy2
  File "C:\dev\tools\python27\lib\site-packages\pymorphy2\__init__.py", line 3, in <module>
    from .analyzer import MorphAnalyzer
  File "C:\dev\tools\python27\lib\site-packages\pymorphy2\analyzer.py", line 13, in <module>
    import pymorphy2.lang
  File "C:\dev\tools\python27\lib\site-packages\pymorphy2\lang\__init__.py", line 3, in <module>
    from . import ru, uk
  File "C:\dev\tools\python27\lib\site-packages\pymorphy2\lang\ru\__init__.py", line 3, in <module>
    from .config import *
  File "C:\dev\tools\python27\lib\site-packages\pymorphy2\lang\ru\config.py", line 6, in <module>
    from pymorphy2 import units
  File "C:\dev\tools\python27\lib\site-packages\pymorphy2\units\__init__.py", line 4, in <module>
    from .by_lookup import DictionaryAnalyzer
  File "C:\dev\tools\python27\lib\site-packages\pymorphy2\units\by_lookup.py", line 8, in <module>
    from pymorphy2.units.base import BaseAnalyzerUnit
  File "C:\dev\tools\python27\lib\site-packages\pymorphy2\units\base.py", line 3, in <module>
    import inspect
  File "C:\dev\tools\python27\lib\inspect.py", line 39, in <module>
    import tokenize
  File "C:\dev\tokenize.py", line 5, in <module>
    morph = pymorphy2.MorphAnalyzer()
AttributeError: 'module' object has no attribute 'MorphAnalyzer'
```

если переименовать `tokenize.py` - то ошибка пропадает, что так же интересно - `pymorphy2` не содержит файлов `tokenize` или `tokenize.py`

**Comment by insolor** [comment]
[tokenize](https://docs.python.org/3/library/tokenize.html) - это стандартный модуль python. Просто не называйте файл так.
