### ISSUE TITLE
проблема с pymorphy2_dicts_ru.get_path()

### ISSUE THREAD

**Issue by etongkeji** [kmike/pymorphy2#148]
проблема с pymorphy2_dicts_ru.get_path()

import pymorphy2
morph = pymorphy2.MorphAnalyzer()
morph.parse('мировой войны')

выводит:

Traceback (most recent call last):
  File "D:\etong\cn02.py", line 2, in <module>
    morph = pymorphy2.MorphAnalyzer(lang='ru')
  File "C:\Users\俄通科技\AppData\Local\Programs\Python\Python39\lib\site-packages\pymorphy2\analyzer.py", line 203, in __init__
    self.dictionary = opencorpora_dict.Dictionary(path)
  File "C:\Users\俄通科技\AppData\Local\Programs\Python\Python39\lib\site-packages\pymorphy2\opencorpora_dict\wrapper.py", line 18, in __init__
    self._data = load_dict(path)
  File "C:\Users\俄通科技\AppData\Local\Programs\Python\Python39\lib\site-packages\pymorphy2\opencorpora_dict\storage.py", line 59, in load_dict
    words = dawg.WordsDawg().load(_f('words.dawg'))
  File "src/dawg.pyx", line 507, in dawg.BytesDAWG.load
  File "src/dawg.pyx", line 398, in dawg.CompletionDAWG.load
OSError: It's not possible to read file stream

**Comment by insolor** [comment]
1. pymorphy2 не парсит предложения или словосочетания, только отдельные слова.
2. Попробуйте переустановить Python по пути не содержащем иероглифов, например в C:\Python39, потом на него установить pymorhphy2
